FROM python:3.8 AS base
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        make curl git wget
RUN useradd -m dev

WORKDIR /home/dev
USER dev

RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv

ENV HOME  /home/dev
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN pyenv install 3.8 3.9 3.10 3.11 3.12 3.13
RUN echo "pyenv global 3.8 3.9 3.10 3.11 3.12 3.13" >> ~/.bashrc

WORKDIR $HOME/hkopendata-py
COPY . .
RUN python -m pip install poetry pre-commit && \
    python -m poetry export -f requirements.txt \
        -o requirements-dev.txt --with dev --without-hashes && \
    python -m pip install -r requirements-dev.txt


