name: docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_mkdocs:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    env:
      DOCS_DIR: docs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          key: mkdocs-material-${{ hashFiles('${{ env.DOC_DIR }}/**') }}
          path: .
          restore-keys: |
            mkdocs-material-
      - name: Setup Pages
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/configure-pages@v5
      - name: Setup Python
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install yamllint
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install yamllint
      - name: Check MkDocs YAML configuration
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{ env.DOCS_DIR }}
        run: yamllint ./mkdocs.yml
        continue-on-error: true
      - name: Install MkDocs Material
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install mkdocs-material
      - name: Build site (_site directory name is used for Jekyll compatiblity)
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{ env.DOCS_DIR }}
        run: mkdocs build --config-file ./mkdocs.yml --strict --site-dir ./_site
        env:
          CI: true
      - name: Upload artifact
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DOCS_DIR }}/_site

  deploy_mkdocs:
    if: needs.build_mkdocs.outputs.cache-hit != 'true'
    environment:
      name: github-pages
    needs: build_mkdocs
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
